# Generated by Django 5.0.2 on 2025-02-22 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_rameurs', models.IntegerField()),
                ('couple', models.BooleanField(default=False)),
                ('barre', models.BooleanField(default=False)),
                ('en_sortie', models.BooleanField(default=False)),
                ('en_reparation', models.BooleanField(default=False)),
                ('prive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rameur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('bateau_immobilise', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('bateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cahierDeSorties.bateau')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cahierDeSorties.rameur')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('bateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cahierDeSorties.bateau')),
            ],
        ),
        migrations.CreateModel(
            name='SortieRameur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rameur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cahierDeSorties.rameur')),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cahierDeSorties.sortie')),
            ],
        ),
    ]
