# Generated by Django 5.0.2 on 2025-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bateau',
            options={'verbose_name_plural': 'Bateaux'},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='bateau_immobilise',
        ),
        migrations.AddField(
            model_name='bateau',
            name='annee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bateau',
            name='immobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bateau',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bateau',
            name='materiau',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bateau',
            name='portance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rameur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rameur',
            name='genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='sortie',
            name='couple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
