# Generated by Django 5.0.2 on 2025-02-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bateau',
            options={'verbose_name_plural': 'Bateaux'},
        ),
    ]
