# Generated by Django 5.0.2 on 2025-02-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0002_alter_bateau_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='couple',
            field=models.BooleanField(default=False),
        ),
    ]
