# Generated by Django 5.0.2 on 2025-08-29 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0002_alter_bateau_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='barreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_barrees', to='cahierDeSorties.rameur'),
        ),
    ]
