# Generated by Django 5.0.2 on 2025-02-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0003_sortie_couple'),
    ]

    operations = [
        migrations.AddField(
            model_name='rameur',
            name='genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1),
        ),
    ]
