# Generated by Django 5.0.2 on 2025-02-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0004_rameur_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rameur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
