# Generated by Django 5.0.2 on 2025-02-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0005_rameur_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
