# Generated by Django 5.0.2 on 2025-02-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0006_alter_sortie_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
