# Generated by Django 5.0.2 on 2025-02-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahierDeSorties', '0007_alter_sortie_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
